from pathlib import Path

TARGET_WINDOW_TITLE = "Notepad"

DB_PATH = "data/runs.db"

TREE_SNAPSHOT_DIR = Path("data/snapshots")

LOOP_TIMEOUT_MIN = 15

DRIFT_RETRY_BACKOFF_SEC = 0.2

RESOLVE_TIMEOUT_SEC = 10

ACTIVE_POLL_SEC = 0.1

DASHBOARD_REFRESH_SEC = 5
